name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      # Use clean install with a fix for the Rollup optional dependencies issue
      - name: Install dependencies
        run: |
          # Remove package-lock.json to avoid npm bug with optional dependencies
          rm -f package-lock.json
          npm install
        
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run typecheck

      # Fix for Vitest/Rollup module issues on Linux runners
      - name: Run tests
        run: |
          # Try to help Rollup find the Linux-specific modules
          export NODE_PATH="$NODE_PATH:$(npm root)"
          # Ensure native modules are installed
          npm rebuild rollup
          # Run tests with specific options for CI
          npx vitest run --mode ci --environment=node